// events.rs - Event Bus and UI Events for decoupled game logic

use macroquad_toolkit::events::EventBus as ToolkitEventBus;

/// UI Events generated by input handling
#[derive(Debug, Clone)]

pub enum UIEvent {
    /// Repair a module at the given grid coordinate
    Repair(usize, usize),
    /// Upgrade a module at the given grid coordinate
    Upgrade(usize, usize),
    /// Toggle a module online/offline at the given grid coordinate
    Toggle(usize, usize),
    /// Pause the game
    Pause,
    /// Resume the game
    Resume,
    /// Return to main menu
    ReturnToMenu,
    /// Start a new game
    StartGame,
    /// Purchase an upgrade by ID
    PurchaseUpgrade(String),
    /// Proceed to next round
    NextRound,
    /// Save game to slot
    SaveGame(usize),
    /// Load game from slot
    LoadGame(usize),
    /// Exit the game
    ExitGame,
}

/// Game events for internal state changes (can be used for audio, particles, etc.)
#[derive(Debug, Clone)]

pub enum GameEvent {
    /// Module was repaired
    ModuleRepaired { x: usize, y: usize, cost: i32 },
    /// Module was upgraded
    ModuleUpgraded { x: usize, y: usize, new_level: u8 },
    /// Module was destroyed
    ModuleDestroyed { x: usize, y: usize },
    /// Enemy was killed
    EnemyKilled { x: f32, y: f32, scrap_dropped: i32 },
    /// Enemy reached and damaged a module
    ModuleDamaged { x: usize, y: usize, damage: f32 },
    /// Core took damage
    CoreDamaged { damage: f32, remaining_hp: f32 },
    /// Engine activated - escape sequence started
    EngineActivated,
    /// A repaired ship system was routed online or offline
    PowerRouted { system: String, powered: bool },
    /// Escape successful
    EscapeSuccess,
    /// Game over - core destroyed
    CoreDestroyed,
    /// Weapon fired a projectile
    WeaponFired { x: f32, y: f32 },
    /// Threat signature crossed into a higher tier
    ThreatEscalated { tier: u8 },
    /// Boss unleashed an EMP pulse that knocked routed systems offline
    EmpPulse,
}

/// Event bus for decoupling UI input from game logic updates: two toolkit
/// event channels, one for UI intents and one for game feedback events.
pub struct EventBus {
    ui_events: ToolkitEventBus<UIEvent>,
    game_events: ToolkitEventBus<GameEvent>,
}

impl EventBus {
    pub fn new() -> Self {
        Self {
            ui_events: ToolkitEventBus::new(),
            game_events: ToolkitEventBus::new(),
        }
    }

    /// Push a UI event to be processed
    pub fn push_ui(&mut self, event: UIEvent) {
        self.ui_events.push(event);
    }

    /// Push a game event (for audio/visual feedback)
    pub fn push_game(&mut self, event: GameEvent) {
        self.game_events.push(event);
    }

    /// Drain all UI events for processing
    pub fn drain_ui(&mut self) -> Vec<UIEvent> {
        self.ui_events.drain().collect()
    }

    /// Drain all game events for processing
    pub fn drain_game(&mut self) -> Vec<GameEvent> {
        self.game_events.drain().collect()
    }
}
